const API_END_POINT = 'http://127.0.0.1:8000/api/';
const API_METHOD_SERIES = 'getseries';
const API_METHOD_COUNT = 'getcountinfo';
const API_METHOD_SERIE_FIGURINE_INFO = 'seriefigurineinfo';
const API_METHOD_YEARS = 'getyears';
const API_METHOD_SERIES_FOR_DECADES = 'seriesForDecades';
const API_METHOD_GENERAL_INFO = 'generalInfo';

export {
  API_END_POINT,
  API_METHOD_SERIES,
  API_METHOD_COUNT,
  API_METHOD_SERIE_FIGURINE_INFO,
  API_METHOD_YEARS,
  API_METHOD_SERIES_FOR_DECADES,
  API_METHOD_GENERAL_INFO,
};
