const API_END_POINT = 'http://127.0.0.1:8000/api/';
const API_METHOD_SERIES = 'getseries';
const API_METHOD_COUNT = 'getcountinfo';
const API_METHOD_SERIE_FIGURINE_INFO = 'seriefigurineinfo';
const API_METHOD_YEARS = 'getyears';
const API_METHOD_SERIES_FOR_DECADES = 'seriesForDecades';
const API_METHOD_GENERAL_INFO = 'generalInfo';
const API_METHOD_FIGURINES_BY_YEAR = 'figurinesByYear';
const API_METHOD_SERIES_DETAIL = 'getseriesdetail';
const API_METHOD_FIGURINE = 'getfigurine';
const API_METHOD_FIGURINE_OF_SERIES = 'getfigurineofseries';
const API_METHOD_COST_OF_SERIES_FIGURINE = 'getcostofseriesfigurine';

export {
  API_END_POINT,
  API_METHOD_SERIES,
  API_METHOD_COUNT,
  API_METHOD_SERIE_FIGURINE_INFO,
  API_METHOD_YEARS,
  API_METHOD_SERIES_FOR_DECADES,
  API_METHOD_GENERAL_INFO,
  API_METHOD_FIGURINES_BY_YEAR,
  API_METHOD_SERIES_DETAIL,
  API_METHOD_FIGURINE,
  API_METHOD_FIGURINE_OF_SERIES,
  API_METHOD_COST_OF_SERIES_FIGURINE,
};
